/** Per-locale labels for the docs architecture diagram.
 *
 *  One entry per site locale, all typed as ArchitectureLabels so the compiler
 *  forces every locale to provide every label — the same discipline as the
 *  app's Messages tables. Brand and provider names (ZenCopy, Google, OpenAI,
 *  Anthropic, Ollama, API) stay untranslated everywhere.
 */

import type { ArchitectureLabels } from "./architecture-diagram.ts";

export type ArchitectureLocale =
  | "ar"
  | "de"
  | "en"
  | "es"
  | "fa"
  | "fr"
  | "he"
  | "id"
  | "it"
  | "ja"
  | "ko"
  | "pl"
  | "pt-br"
  | "ru"
  | "th"
  | "tr"
  | "vi"
  | "zh-hans"
  | "zh-hant";

/** Locales whose diagram mirrors right-to-left. */
export const RTL_ARCHITECTURE_LOCALES: ReadonlySet<string> = new Set(["ar", "fa", "he"]);

export const ARCHITECTURE_LABELS: Record<ArchitectureLocale, ArchitectureLabels> = {
  ar: {
    alt: "مخطط كامل لتدفق البيانات في ZenCopy: انسخ مرتين على الشاشة الحالية فيرسل ZenCopy المحتوى والموجّه مباشرة إلى الذكاء الاصطناعي الذي اخترته، وتصل الإجابة إلى النافذة المنبثقة، وتبقى المفاتيح والإعدادات على حاسوبك فقط",
    pcZone: "حاسوبك",
    screen: "الشاشة الحالية",
    screenSub: "نصوص وصور وملفات",
    flowCopy: "انسخ مرتين",
    zcStep1: "اكتشاف النسخ المزدوج",
    zcStep2: "التوجيه وفق القواعد",
    zcStep3: "تجهيز الموجّه",
    flowSend: "المحتوى المنسوخ والموجّه",
    flowSendNote1: "اتصال مباشر",
    flowSendNote2: "لا خادم وسيط لـ ZenCopy ولا قياس عن بُعد",
    flowAnswer: "الإجابة (متدفقة)",
    ai: "الذكاء الاصطناعي المختار",
    aiLine1: "Google، OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "بوابة (Gateway)",
    aiLine4: "Ollama (محليًا)",
    flowShow: "عرض الإجابة",
    flowReply: "متابعة المحادثة",
    popup: "النافذة المنبثقة",
    popupSub: "تظهر في زاوية الشاشة",
    popupNote: "المحادثات لا تُحفظ",
    storageRead: "قراءة مفاتيح API والقواعد",
    storageWrite: "كتابة الإحصاءات والسجلات",
    storage: "مجلد الإعدادات والسجلات",
    storageLine1: "مفاتيح API والإعدادات",
    storageLine2: "الموجّهات وقواعد التوجيه",
    storageLine3: "إحصاءات الاستخدام والسجلات",
    storageNote1: "لا تحتوي السجلات على المحتوى المنسوخ",
    storageNote2: "لا يُرسل أي من ذلك إلى أي مكان",
  },
  de: {
    alt: "Vollständiges Datenflussdiagramm von ZenCopy: Zweimal Kopieren auf dem sichtbaren Bildschirm, ZenCopy sendet Inhalt und Prompt direkt an die gewählte KI, die Antwort erscheint im Popup, und Schlüssel und Einstellungen bleiben allein auf Ihrem Computer",
    pcZone: "Ihr Computer",
    screen: "Ihr aktueller Bildschirm",
    screenSub: "Texte, Bilder und Dateien",
    flowCopy: "Zweimal kopieren",
    zcStep1: "Zweimal-Kopieren erkennen",
    zcStep2: "Nach Regeln zuordnen",
    zcStep3: "Prompt zusammenstellen",
    flowSend: "Kopierter Inhalt und Prompt",
    flowSendNote1: "Direkte Verbindung",
    flowSendNote2: "Kein ZenCopy-Relay, keine Telemetrie",
    flowAnswer: "Antwort (gestreamt)",
    ai: "Die gewählte KI",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Gateway",
    aiLine4: "Ollama (lokal)",
    flowShow: "Antwort anzeigen",
    flowReply: "Weiterführendes Gespräch",
    popup: "Das Popup",
    popupSub: "Erscheint in der Bildschirmecke",
    popupNote: "Gespräche werden nicht gespeichert",
    storageRead: "API-Schlüssel und Regeln lesen",
    storageWrite: "Statistik und Logs schreiben",
    storage: "Einstellungsordner und Logs",
    storageLine1: "API-Schlüssel und Einstellungen",
    storageLine2: "Prompts und Zuordnungsregeln",
    storageLine3: "Nutzungsstatistik und Logs",
    storageNote1: "Logs enthalten keine kopierten Inhalte",
    storageNote2: "Nichts davon wird irgendwohin gesendet",
  },
  en: {
    alt: "Full data-flow diagram of ZenCopy: copy twice on the screen you are looking at, ZenCopy sends the content and a prompt directly to the AI you chose, the answer streams into the popup, and keys and settings stay only on your computer",
    pcZone: "Your computer",
    screen: "Your current screen",
    screenSub: "Text, images, files",
    flowCopy: "Copy twice",
    zcStep1: "Detects the double copy",
    zcStep2: "Routes by rules",
    zcStep3: "Builds the prompt",
    flowSend: "Copied content and prompt",
    flowSendNote1: "Direct connection",
    flowSendNote2: "No ZenCopy relay, no telemetry",
    flowAnswer: "Answer (streamed)",
    ai: "The AI you chose",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Gateway",
    aiLine4: "Ollama (local)",
    flowShow: "Show the answer",
    flowReply: "Follow-up conversation",
    popup: "The popup",
    popupSub: "Appears in a screen corner",
    popupNote: "Conversations are not saved",
    storageRead: "Read API keys and rules",
    storageWrite: "Write stats and logs",
    storage: "Settings folder and logs",
    storageLine1: "API keys and settings",
    storageLine2: "Prompts and routing rules",
    storageLine3: "Usage statistics and logs",
    storageNote1: "Logs never contain copied content",
    storageNote2: "None of it is sent anywhere",
  },
  es: {
    alt: "Diagrama completo del flujo de datos de ZenCopy: copia dos veces en tu pantalla actual, ZenCopy envía el contenido y un prompt directamente a la IA que elegiste, la respuesta llega a la ventana emergente y las claves y ajustes se quedan solo en tu equipo",
    pcZone: "Tu equipo",
    screen: "Tu pantalla actual",
    screenSub: "Texto, imágenes y archivos",
    flowCopy: "Copiar dos veces",
    zcStep1: "Detecta la doble copia",
    zcStep2: "Enruta según las reglas",
    zcStep3: "Prepara el prompt",
    flowSend: "Contenido copiado y prompt",
    flowSendNote1: "Conexión directa",
    flowSendNote2: "Sin relé de ZenCopy ni telemetría",
    flowAnswer: "Respuesta (en streaming)",
    ai: "La IA que elegiste",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Pasarela (gateway)",
    aiLine4: "Ollama (local)",
    flowShow: "Mostrar la respuesta",
    flowReply: "Continuar la conversación",
    popup: "La ventana emergente",
    popupSub: "En una esquina de la pantalla",
    popupNote: "Las conversaciones no se guardan",
    storageRead: "Lee claves API y reglas",
    storageWrite: "Escribe estadísticas y registros",
    storage: "Carpeta de ajustes y registros",
    storageLine1: "Claves API y ajustes",
    storageLine2: "Prompts y reglas de enrutado",
    storageLine3: "Estadísticas de uso y registros",
    storageNote1: "Los registros nunca contienen lo copiado",
    storageNote2: "Nada de esto se envía a ningún sitio",
  },
  fa: {
    alt: "نمودار کامل جریان داده در ZenCopy: روی صفحهٔ کنونی دوبار کپی کنید تا ZenCopy محتوا و پرامپت را مستقیم به هوش مصنوعی انتخابی شما بفرستد، پاسخ در پنجرهٔ بازشو ظاهر شود و کلیدها و تنظیمات فقط روی رایانهٔ شما بمانند",
    pcZone: "رایانهٔ شما",
    screen: "صفحهٔ کنونی",
    screenSub: "متن، تصویر و فایل",
    flowCopy: "دوبار کپی",
    zcStep1: "تشخیص دوبار کپی",
    zcStep2: "مسیریابی طبق قواعد",
    zcStep3: "آماده‌سازی پرامپت",
    flowSend: "محتوای کپی‌شده و پرامپت",
    flowSendNote1: "اتصال مستقیم",
    flowSendNote2: "بدون سرور واسط ZenCopy و بدون تله‌متری",
    flowAnswer: "پاسخ (استریم‌شده)",
    ai: "هوش مصنوعی انتخابی شما",
    aiLine1: "Google، OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "درگاه (Gateway)",
    aiLine4: "Ollama (محلی)",
    flowShow: "نمایش پاسخ",
    flowReply: "ادامهٔ گفت‌وگو",
    popup: "پنجرهٔ بازشو",
    popupSub: "در گوشهٔ صفحه ظاهر می‌شود",
    popupNote: "گفت‌وگوها ذخیره نمی‌شوند",
    storageRead: "خواندن کلیدهای API و قواعد",
    storageWrite: "نوشتن آمار و لاگ‌ها",
    storage: "پوشهٔ تنظیمات و لاگ‌ها",
    storageLine1: "کلیدهای API و تنظیمات",
    storageLine2: "پرامپت‌ها و قواعد مسیریابی",
    storageLine3: "آمار استفاده و لاگ‌ها",
    storageNote1: "لاگ‌ها هرگز حاوی محتوای کپی‌شده نیستند",
    storageNote2: "هیچ‌کدام به جایی فرستاده نمی‌شود",
  },
  fr: {
    alt: "Diagramme complet du flux de données de ZenCopy : copiez deux fois sur votre écran actuel, ZenCopy envoie le contenu et un prompt directement à l'IA de votre choix, la réponse arrive dans la fenêtre contextuelle, et les clés et les réglages restent uniquement sur votre ordinateur",
    pcZone: "Votre ordinateur",
    screen: "Votre écran actuel",
    screenSub: "Texte, images et fichiers",
    flowCopy: "Copier deux fois",
    zcStep1: "Détecte la double copie",
    zcStep2: "Aiguille selon les règles",
    zcStep3: "Compose le prompt",
    flowSend: "Contenu copié et prompt",
    flowSendNote1: "Connexion directe",
    flowSendNote2: "Aucun relais ZenCopy, aucune télémétrie",
    flowAnswer: "Réponse (en continu)",
    ai: "L'IA de votre choix",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Passerelle (gateway)",
    aiLine4: "Ollama (local)",
    flowShow: "Afficher la réponse",
    flowReply: "Suite de la conversation",
    popup: "La fenêtre contextuelle",
    popupSub: "Apparaît dans un coin de l'écran",
    popupNote: "Les conversations ne sont pas conservées",
    storageRead: "Lit les clés API et les règles",
    storageWrite: "Écrit statistiques et journaux",
    storage: "Dossier des réglages et journaux",
    storageLine1: "Clés API et réglages",
    storageLine2: "Prompts et règles d'aiguillage",
    storageLine3: "Statistiques d'usage et journaux",
    storageNote1: "Aucun contenu copié dans les journaux",
    storageNote2: "Rien de tout cela n'est envoyé nulle part",
  },
  he: {
    alt: "תרשים מלא של זרימת הנתונים ב‑ZenCopy: מעתיקים פעמיים במסך הנוכחי, ZenCopy שולח את התוכן ואת הפרומפט ישירות ל‑AI שבחרת, התשובה מגיעה לחלון הקופץ, והמפתחות וההגדרות נשארים רק במחשב שלך",
    pcZone: "המחשב שלך",
    screen: "המסך הנוכחי",
    screenSub: "טקסט, תמונות וקבצים",
    flowCopy: "העתקה פעמיים",
    zcStep1: "זיהוי ההעתקה הכפולה",
    zcStep2: "ניתוב לפי הכללים",
    zcStep3: "הרכבת הפרומפט",
    flowSend: "התוכן שהועתק והפרומפט",
    flowSendNote1: "חיבור ישיר",
    flowSendNote2: "בלי שרת ביניים של ZenCopy ובלי טלמטריה",
    flowAnswer: "התשובה (בהזרמה)",
    ai: "ה‑AI שבחרת",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "שער (Gateway)",
    aiLine4: "Ollama (מקומי)",
    flowShow: "הצגת התשובה",
    flowReply: "המשך השיחה",
    popup: "החלון הקופץ",
    popupSub: "מופיע בפינת המסך",
    popupNote: "שיחות אינן נשמרות",
    storageRead: "קריאת מפתחות API וכללים",
    storageWrite: "כתיבת סטטיסטיקה ויומנים",
    storage: "תיקיית ההגדרות והיומנים",
    storageLine1: "מפתחות API והגדרות",
    storageLine2: "פרומפטים וכללי ניתוב",
    storageLine3: "סטטיסטיקת שימוש ויומנים",
    storageNote1: "היומנים לעולם אינם מכילים תוכן שהועתק",
    storageNote2: "דבר מזה אינו נשלח לשום מקום",
  },
  id: {
    alt: "Diagram lengkap alur data ZenCopy: salin dua kali di layar saat ini, ZenCopy mengirim konten dan prompt langsung ke AI pilihan Anda, jawaban muncul di popup, dan kunci serta pengaturan hanya tersimpan di komputer Anda",
    pcZone: "Komputer Anda",
    screen: "Layar saat ini",
    screenSub: "Teks, gambar, dan berkas",
    flowCopy: "Salin dua kali",
    zcStep1: "Mendeteksi penyalinan ganda",
    zcStep2: "Mengarahkan sesuai aturan",
    zcStep3: "Menyusun prompt",
    flowSend: "Konten tersalin dan prompt",
    flowSendNote1: "Koneksi langsung",
    flowSendNote2: "Tanpa relai ZenCopy, tanpa telemetri",
    flowAnswer: "Jawaban (streaming)",
    ai: "AI pilihan Anda",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Gateway",
    aiLine4: "Ollama (lokal)",
    flowShow: "Menampilkan jawaban",
    flowReply: "Lanjutan percakapan",
    popup: "Popup",
    popupSub: "Muncul di sudut layar",
    popupNote: "Percakapan tidak disimpan",
    storageRead: "Membaca kunci API dan aturan",
    storageWrite: "Mencatat statistik dan log",
    storage: "Folder pengaturan dan log",
    storageLine1: "Kunci API dan pengaturan",
    storageLine2: "Prompt dan aturan perutean",
    storageLine3: "Statistik penggunaan dan log",
    storageNote1: "Log tidak pernah memuat konten salinan",
    storageNote2: "Tidak ada yang dikirim ke mana pun",
  },
  it: {
    alt: "Diagramma completo del flusso dati di ZenCopy: copia due volte sulla schermata attuale, ZenCopy invia contenuto e prompt direttamente all'IA che hai scelto, la risposta arriva nel popup e chiavi e impostazioni restano solo sul tuo computer",
    pcZone: "Il tuo computer",
    screen: "La schermata attuale",
    screenSub: "Testo, immagini e file",
    flowCopy: "Copia due volte",
    zcStep1: "Rileva la doppia copia",
    zcStep2: "Smista secondo le regole",
    zcStep3: "Prepara il prompt",
    flowSend: "Contenuto copiato e prompt",
    flowSendNote1: "Connessione diretta",
    flowSendNote2: "Nessun relay ZenCopy, nessuna telemetria",
    flowAnswer: "Risposta (in streaming)",
    ai: "L'IA che hai scelto",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Gateway",
    aiLine4: "Ollama (locale)",
    flowShow: "Mostra la risposta",
    flowReply: "Seguito della conversazione",
    popup: "Il popup",
    popupSub: "Appare in un angolo dello schermo",
    popupNote: "Le conversazioni non vengono salvate",
    storageRead: "Legge chiavi API e regole",
    storageWrite: "Scrive statistiche e log",
    storage: "Cartella impostazioni e log",
    storageLine1: "Chiavi API e impostazioni",
    storageLine2: "Prompt e regole di smistamento",
    storageLine3: "Statistiche d'uso e log",
    storageNote1: "I log non contengono mai ciò che copi",
    storageNote2: "Nulla di tutto ciò viene inviato altrove",
  },
  ja: {
    alt: "ZenCopy の全データフロー図。今見ている画面でコピーを 2 回すると、ZenCopy が内容とプロンプトを選んだ AI（インターネット上のサービス、社内ゲートウェイ、ローカルの Ollama など）へ直接送り、答えがポップアップに流れる。API キーや設定、ログはパソコンの中に保存され、どこにも送信されない",
    pcZone: "あなたのパソコン",
    screen: "今見ている画面",
    screenSub: "文章、画像、ファイル",
    flowCopy: "コピー 2 回",
    zcStep1: "コピー 2 回を検知",
    zcStep2: "ルールで振り分け",
    zcStep3: "プロンプトを組み立て",
    flowSend: "コピーした内容とプロンプト",
    flowSendNote1: "直接通信します",
    flowSendNote2: "ZenCopy の中継サーバーやテレメトリなどはありません",
    flowAnswer: "答え（ストリーミング）",
    ai: "選んだ AI",
    aiLine1: "Google、OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "ゲートウェイ",
    aiLine4: "Ollama（ローカル）",
    flowShow: "答えを表示",
    flowReply: "続きの会話",
    popup: "ポップアップ",
    popupSub: "画面の隅に表示",
    popupNote: "会話は保存されません",
    storageRead: "API キーやルールを読む",
    storageWrite: "統計とログを書く",
    storage: "設定フォルダとログ",
    storageLine1: "API キーと設定",
    storageLine2: "プロンプトと振り分けルール",
    storageLine3: "利用統計とログ",
    storageNote1: "ログにコピーした内容は残しません",
    storageNote2: "中身はどこにも送信されません",
  },
  ko: {
    alt: "ZenCopy의 전체 데이터 흐름도: 지금 보는 화면에서 두 번 복사하면 ZenCopy가 내용과 프롬프트를 선택한 AI로 직접 보내고, 답변이 팝업에 표시되며, 키와 설정은 내 컴퓨터에만 저장됩니다",
    pcZone: "내 컴퓨터",
    screen: "지금 보고 있는 화면",
    screenSub: "텍스트, 이미지, 파일",
    flowCopy: "두 번 복사",
    zcStep1: "두 번 복사 감지",
    zcStep2: "규칙으로 분기",
    zcStep3: "프롬프트 구성",
    flowSend: "복사한 내용과 프롬프트",
    flowSendNote1: "직접 연결",
    flowSendNote2: "ZenCopy 중계 서버나 텔레메트리가 없습니다",
    flowAnswer: "답변(스트리밍)",
    ai: "선택한 AI",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "게이트웨이",
    aiLine4: "Ollama(로컬)",
    flowShow: "답변 표시",
    flowReply: "이어지는 대화",
    popup: "팝업",
    popupSub: "화면 구석에 표시",
    popupNote: "대화는 저장되지 않습니다",
    storageRead: "API 키와 규칙 읽기",
    storageWrite: "통계와 로그 쓰기",
    storage: "설정 폴더와 로그",
    storageLine1: "API 키와 설정",
    storageLine2: "프롬프트와 분기 규칙",
    storageLine3: "사용 통계와 로그",
    storageNote1: "로그에 복사한 내용은 남지 않습니다",
    storageNote2: "이 중 무엇도 어디로도 전송되지 않습니다",
  },
  pl: {
    alt: "Pełny diagram przepływu danych w ZenCopy: skopiuj dwa razy na bieżącym ekranie, ZenCopy wysyła treść i prompt bezpośrednio do wybranej AI, odpowiedź trafia do okienka, a klucze i ustawienia zostają tylko na Twoim komputerze",
    pcZone: "Twój komputer",
    screen: "Bieżący ekran",
    screenSub: "Tekst, obrazy i pliki",
    flowCopy: "Skopiuj dwa razy",
    zcStep1: "Wykrywa podwójne kopiowanie",
    zcStep2: "Kieruje według reguł",
    zcStep3: "Składa prompt",
    flowSend: "Skopiowana treść i prompt",
    flowSendNote1: "Połączenie bezpośrednie",
    flowSendNote2: "Bez serwera pośredniczącego ZenCopy i telemetrii",
    flowAnswer: "Odpowiedź (strumieniowo)",
    ai: "Wybrana AI",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Bramka (gateway)",
    aiLine4: "Ollama (lokalnie)",
    flowShow: "Wyświetla odpowiedź",
    flowReply: "Dalsza rozmowa",
    popup: "Okienko",
    popupSub: "Pojawia się w rogu ekranu",
    popupNote: "Rozmowy nie są zapisywane",
    storageRead: "Odczyt kluczy API i reguł",
    storageWrite: "Zapis statystyk i logów",
    storage: "Folder ustawień i logi",
    storageLine1: "Klucze API i ustawienia",
    storageLine2: "Prompty i reguły kierowania",
    storageLine3: "Statystyki użycia i logi",
    storageNote1: "Logi nie zawierają kopiowanej treści",
    storageNote2: "Nic z tego nie jest nigdzie wysyłane",
  },
  "pt-br": {
    alt: "Diagrama completo do fluxo de dados do ZenCopy: copie duas vezes na tela atual, o ZenCopy envia o conteúdo e um prompt diretamente à IA que você escolheu, a resposta chega ao popup e as chaves e configurações ficam apenas no seu computador",
    pcZone: "Seu computador",
    screen: "Sua tela atual",
    screenSub: "Texto, imagens e arquivos",
    flowCopy: "Copiar duas vezes",
    zcStep1: "Detecta a cópia dupla",
    zcStep2: "Roteia pelas regras",
    zcStep3: "Monta o prompt",
    flowSend: "Conteúdo copiado e prompt",
    flowSendNote1: "Conexão direta",
    flowSendNote2: "Sem relay do ZenCopy, sem telemetria",
    flowAnswer: "Resposta (em streaming)",
    ai: "A IA que você escolheu",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Gateway",
    aiLine4: "Ollama (local)",
    flowShow: "Mostrar a resposta",
    flowReply: "Continuação da conversa",
    popup: "O popup",
    popupSub: "Aparece no canto da tela",
    popupNote: "As conversas não são salvas",
    storageRead: "Lê chaves de API e regras",
    storageWrite: "Grava estatísticas e logs",
    storage: "Pasta de configurações e logs",
    storageLine1: "Chaves de API e configurações",
    storageLine2: "Prompts e regras de roteamento",
    storageLine3: "Estatísticas de uso e logs",
    storageNote1: "Os logs nunca contêm o conteúdo copiado",
    storageNote2: "Nada disso é enviado a lugar algum",
  },
  ru: {
    alt: "Полная схема потоков данных ZenCopy: скопируйте дважды на текущем экране, ZenCopy отправит содержимое и промпт напрямую выбранному ИИ, ответ появится во всплывающем окне, а ключи и настройки останутся только на вашем компьютере",
    pcZone: "Ваш компьютер",
    screen: "Текущий экран",
    screenSub: "Текст, изображения, файлы",
    flowCopy: "Скопируйте дважды",
    zcStep1: "Обнаруживает двойное копирование",
    zcStep2: "Направляет по правилам",
    zcStep3: "Собирает промпт",
    flowSend: "Скопированное содержимое и промпт",
    flowSendNote1: "Прямое соединение",
    flowSendNote2: "Без сервера-посредника ZenCopy и телеметрии",
    flowAnswer: "Ответ (потоком)",
    ai: "Выбранный ИИ",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Шлюз (gateway)",
    aiLine4: "Ollama (локально)",
    flowShow: "Показывает ответ",
    flowReply: "Продолжение разговора",
    popup: "Всплывающее окно",
    popupSub: "Появляется в углу экрана",
    popupNote: "Разговоры не сохраняются",
    storageRead: "Читает ключи API и правила",
    storageWrite: "Записывает статистику и логи",
    storage: "Папка настроек и логи",
    storageLine1: "Ключи API и настройки",
    storageLine2: "Промпты и правила маршрутизации",
    storageLine3: "Статистика использования и логи",
    storageNote1: "В логах нет скопированного содержимого",
    storageNote2: "Ничто из этого никуда не отправляется",
  },
  th: {
    alt: "แผนภาพการไหลของข้อมูลทั้งหมดของ ZenCopy: คัดลอกสองครั้งบนหน้าจอปัจจุบัน ZenCopy จะส่งเนื้อหาและพรอมป์ตตรงไปยัง AI ที่คุณเลือก คำตอบจะปรากฏในป๊อปอัป ส่วนคีย์และการตั้งค่าจะอยู่บนคอมพิวเตอร์ของคุณเท่านั้น",
    pcZone: "คอมพิวเตอร์ของคุณ",
    screen: "หน้าจอปัจจุบัน",
    screenSub: "ข้อความ รูปภาพ ไฟล์",
    flowCopy: "คัดลอกสองครั้ง",
    zcStep1: "ตรวจจับการคัดลอกสองครั้ง",
    zcStep2: "จัดเส้นทางตามกฎ",
    zcStep3: "สร้างพรอมป์ต",
    flowSend: "เนื้อหาที่คัดลอกและพรอมป์ต",
    flowSendNote1: "เชื่อมต่อโดยตรง",
    flowSendNote2: "ไม่มีเซิร์ฟเวอร์กลางของ ZenCopy ไม่มีเทเลเมทรี",
    flowAnswer: "คำตอบ (สตรีมมิง)",
    ai: "AI ที่คุณเลือก",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "เกตเวย์",
    aiLine4: "Ollama (ในเครื่อง)",
    flowShow: "แสดงคำตอบ",
    flowReply: "สนทนาต่อ",
    popup: "ป๊อปอัป",
    popupSub: "ปรากฏที่มุมหน้าจอ",
    popupNote: "บทสนทนาไม่ถูกบันทึก",
    storageRead: "อ่านคีย์ API และกฎ",
    storageWrite: "บันทึกสถิติและล็อก",
    storage: "โฟลเดอร์การตั้งค่าและล็อก",
    storageLine1: "คีย์ API และการตั้งค่า",
    storageLine2: "พรอมป์ตและกฎการจัดเส้นทาง",
    storageLine3: "สถิติการใช้งานและล็อก",
    storageNote1: "ล็อกไม่มีเนื้อหาที่คัดลอกไว้",
    storageNote2: "ทั้งหมดนี้ไม่ถูกส่งไปที่ใด",
  },
  tr: {
    alt: "ZenCopy'nin eksiksiz veri akışı diyagramı: geçerli ekranda iki kez kopyalayın, ZenCopy içeriği ve istemi doğrudan seçtiğiniz yapay zekâya gönderir, yanıt açılır pencerede belirir; anahtarlar ve ayarlar yalnızca bilgisayarınızda kalır",
    pcZone: "Bilgisayarınız",
    screen: "Geçerli ekran",
    screenSub: "Metin, görsel ve dosyalar",
    flowCopy: "İki kez kopyala",
    zcStep1: "Çift kopyalamayı algılar",
    zcStep2: "Kurallara göre yönlendirir",
    zcStep3: "İstemi hazırlar",
    flowSend: "Kopyalanan içerik ve istem",
    flowSendNote1: "Doğrudan bağlantı",
    flowSendNote2: "ZenCopy aracı sunucusu ve telemetri yok",
    flowAnswer: "Yanıt (akış halinde)",
    ai: "Seçtiğiniz yapay zekâ",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Ağ geçidi (gateway)",
    aiLine4: "Ollama (yerel)",
    flowShow: "Yanıtı gösterir",
    flowReply: "Sohbetin devamı",
    popup: "Açılır pencere",
    popupSub: "Ekranın köşesinde belirir",
    popupNote: "Sohbetler kaydedilmez",
    storageRead: "API anahtarlarını ve kuralları okur",
    storageWrite: "İstatistik ve günlükleri yazar",
    storage: "Ayar klasörü ve günlükler",
    storageLine1: "API anahtarları ve ayarlar",
    storageLine2: "İstemler ve yönlendirme kuralları",
    storageLine3: "Kullanım istatistikleri ve günlükler",
    storageNote1: "Günlüklerde kopyalanan içerik bulunmaz",
    storageNote2: "Bunların hiçbiri hiçbir yere gönderilmez",
  },
  vi: {
    alt: "Sơ đồ đầy đủ luồng dữ liệu của ZenCopy: sao chép hai lần trên màn hình hiện tại, ZenCopy gửi nội dung và prompt thẳng đến AI bạn đã chọn, câu trả lời hiện trong cửa sổ bật lên, còn khóa và cài đặt chỉ nằm trên máy tính của bạn",
    pcZone: "Máy tính của bạn",
    screen: "Màn hình hiện tại",
    screenSub: "Văn bản, hình ảnh, tệp",
    flowCopy: "Sao chép hai lần",
    zcStep1: "Phát hiện sao chép hai lần",
    zcStep2: "Phân luồng theo quy tắc",
    zcStep3: "Soạn prompt",
    flowSend: "Nội dung đã sao chép và prompt",
    flowSendNote1: "Kết nối trực tiếp",
    flowSendNote2: "Không máy chủ trung gian ZenCopy, không telemetry",
    flowAnswer: "Câu trả lời (truyền liên tục)",
    ai: "AI bạn đã chọn",
    aiLine1: "Google, OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "Gateway",
    aiLine4: "Ollama (cục bộ)",
    flowShow: "Hiển thị câu trả lời",
    flowReply: "Tiếp tục hội thoại",
    popup: "Cửa sổ bật lên",
    popupSub: "Hiện ở góc màn hình",
    popupNote: "Hội thoại không được lưu",
    storageRead: "Đọc khóa API và quy tắc",
    storageWrite: "Ghi thống kê và nhật ký",
    storage: "Thư mục cài đặt và nhật ký",
    storageLine1: "Khóa API và cài đặt",
    storageLine2: "Prompt và quy tắc phân luồng",
    storageLine3: "Thống kê sử dụng và nhật ký",
    storageNote1: "Nhật ký không chứa nội dung đã sao chép",
    storageNote2: "Không có dữ liệu nào được gửi đi",
  },
  "zh-hans": {
    alt: "ZenCopy 的完整数据流图：在当前屏幕上复制两次，ZenCopy 将内容和提示词直接发送给你选择的 AI，回答流入弹窗，密钥和设置只保存在你的电脑上",
    pcZone: "你的电脑",
    screen: "当前屏幕",
    screenSub: "文字、图片、文件",
    flowCopy: "复制两次",
    zcStep1: "识别两次复制",
    zcStep2: "按规则分流",
    zcStep3: "组装提示词",
    flowSend: "复制的内容与提示词",
    flowSendNote1: "直接通信",
    flowSendNote2: "没有 ZenCopy 中转服务器，也没有遥测",
    flowAnswer: "回答（流式）",
    ai: "你选择的 AI",
    aiLine1: "Google、OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "网关",
    aiLine4: "Ollama（本地）",
    flowShow: "显示回答",
    flowReply: "继续对话",
    popup: "弹窗",
    popupSub: "出现在屏幕角落",
    popupNote: "对话不会被保存",
    storageRead: "读取 API 密钥和规则",
    storageWrite: "写入统计和日志",
    storage: "设置文件夹与日志",
    storageLine1: "API 密钥与设置",
    storageLine2: "提示词与分流规则",
    storageLine3: "使用统计与日志",
    storageNote1: "日志不会记录复制的内容",
    storageNote2: "以上内容都不会被发送到任何地方",
  },
  "zh-hant": {
    alt: "ZenCopy 的完整資料流圖：在目前畫面上複製兩次，ZenCopy 會把內容和提示詞直接傳給你選擇的 AI，回答流入彈出視窗，金鑰與設定只保存在你的電腦上",
    pcZone: "你的電腦",
    screen: "目前畫面",
    screenSub: "文字、圖片、檔案",
    flowCopy: "複製兩次",
    zcStep1: "偵測兩次複製",
    zcStep2: "依規則分流",
    zcStep3: "組合提示詞",
    flowSend: "複製的內容與提示詞",
    flowSendNote1: "直接連線",
    flowSendNote2: "沒有 ZenCopy 中繼伺服器，也沒有遙測",
    flowAnswer: "回答（串流）",
    ai: "你選擇的 AI",
    aiLine1: "Google、OpenAI",
    aiLine2: "Anthropic",
    aiLine3: "閘道 (gateway)",
    aiLine4: "Ollama（本機）",
    flowShow: "顯示回答",
    flowReply: "繼續對話",
    popup: "彈出視窗",
    popupSub: "出現在螢幕角落",
    popupNote: "對話不會被儲存",
    storageRead: "讀取 API 金鑰與規則",
    storageWrite: "寫入統計與日誌",
    storage: "設定資料夾與日誌",
    storageLine1: "API 金鑰與設定",
    storageLine2: "提示詞與分流規則",
    storageLine3: "使用統計與日誌",
    storageNote1: "日誌不會留下複製的內容",
    storageNote2: "以上都不會被傳送到任何地方",
  },
};
